### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by DmitryMyadzelets** [ryankurte/jfsm#1]
Execution of the example from README results in the error.
`make language-c`
(skipped for brevity)
`State machine generation complete
gcc outputs/UMLStateMachine-main.c outputs/UMLStateMachine-stubs.c outputs/UMLStateMachine.c -o outputs/UMLStateMachine.o -lreadline
outputs/UMLStateMachine-main.c:12:31: fatal error: readline/readline.h: No such file or directory
compilation terminated.
make: *** [language-c] Error 1`

**Comment by ryankurte** [comment]
I have updated the readme.
Try installing libreadline-dev using your OS package manager, it is used in the demonstration stubs to make a primitive CLI.

**Comment by DmitryMyadzelets** [comment]
Thanks, it works now. I'd add to the readme an example of command: `sudo apt-get install libreadline-dev`.
`
